import Head from 'next/head'
import { useEffect } from 'react'
import About from '../Components/HomePage/About'
import Education from '../Components/HomePage/Education'
import Experience from '../Components/HomePage/Experience'
import Poster from '../Components/HomePage/Poster'
import ReachOut from '../Components/HomePage/ReachOut'
import useData from '../handlers'



// export async function getServerSideProps(){
//   // console.log(process.env.NEXT_PUBLIC_API_KEY)

//   return {
//     props: {
//       'e':'er'
//     }
//   }
// }



export default function Home() {
  const { data, getData } = useData();

  useEffect(() => {
    async function onPageLoad (){
      await getData();
    }
    onPageLoad();
  },[]);
  // const newData = await getStaticProps();
  return (
    <div>
      <Head>
        <title>Manasi Deshpande</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {
        data && (
          <>
            <Poster />
            <About about={data[4].data.records[0].fields} />
            <Education education={data[3].data.records} />
            <Experience experience={data[0].data.records} certification={data[2].data.records} />
            <ReachOut platforms={data[1].data.records} />
          </>
        )
        }
    </div>
  )
}
