import Head from 'next/head'
import About from '../Components/HomePage/About'
import Education from '../Components/HomePage/Education'
import Experience from '../Components/HomePage/Experience'
import Poster from '../Components/HomePage/Poster'
import ReachOut from '../Components/HomePage/ReachOut'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Poster />
      <About />
      <Education />
      <Experience />
      <ReachOut />
    </div>
  )
}
